# This workflow will add services from nlp repo using git submodules

name: NLP Integration

on:
  push:
    branches: [ example ] # will change this later

jobs:
  add:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Add services
      run: echo "Adding ..."
