name: Backed Deployment

on:
  push:
    branch: testing/Testing-scripts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build 
      run: docker build . -t ynlp
    - name: Docker run
      run: docker run --detach --name backend --publish 80:80 ynlp
    - name: testing docker
      run: bash docker_ip.sh
