name: Backed Deployment

on:
  push:
    branch: testing/Testing-scripts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build tiangolo/uvicorn-gunicorn-fastapi
      run: docker build . -t fastapi_ynlp
    - name: Docker run
      run: docker run --detach --publish 80:80 fastapi_ynlp
    - name: testing docker
      run: bash docker_ip.sh
